name: kit
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  fpdart: ^1.1.1
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  animation_list: ^3.1.0
  flutter_secure_storage: ^9.2.4
  modal_bottom_sheet: ^3.0.0
  image_picker: ^1.2.0
  wechat_assets_picker: ^9.8.0
  video_player: ^2.10.0
  video_thumbnail: ^0.5.3
  flutter_isolate: ^2.1.0
  fluttertoast: ^9.0.0
  flutter_svg: ^2.2.1
  flutter_markdown: ^0.7.3

  # State Management
  flutter_bloc: ^9.1.1
  hydrated_bloc: ^10.1.1

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  
  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.5.2

  # Network
  dio: ^5.9.0
  
  # Local Storage
  shared_preferences: ^2.5.3

  sqflite: 2.4.2
  # Firebase
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.3
  firebase_analytics: ^12.0.2
  
  # Notifications
  flutter_local_notifications: ^19.5.0

  # Routing
  go_router: ^16.2.4
  # Other utilities
  http: ^1.5.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  haptic_feedback: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  build_runner: ^2.9.0
  json_serializable: ^6.11.1
  injectable_generator: ^2.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
  fonts:
   - family: Nunito
     fonts:
       - asset: assets/fonts/Nunito-Regular.ttf
       - asset: assets/fonts/Nunito-Medium.ttf
         weight: 500
       - asset: assets/fonts/Nunito-Bold.ttf
         weight: 700
       - asset: assets/fonts/Nunito-Light.ttf
         weight: 300
       - asset: assets/fonts/Nunito-SemiBold.ttf
         weight: 600
       - asset: assets/fonts/Nunito-ExtraBold.ttf
         weight: 800
       - asset: assets/fonts/Nunito-Black.ttf
       - asset: assets/fonts/Nunito-Italic-VariableFont_wght.ttf
         style: italic

flutter_native_splash:
  android: true
  ios: true
  web: false

  # --- Splash mặc định (Android <12, iOS)
  color: "#ffffff"        # ← nền trắng
  image: assets/images/logo.png

  # --- Dark mode (tùy chọn)
  color_dark: "#000000"   # ← khi dark mode, nếu muốn có nền đen
  # image_dark: assets/images/logo_dark.png

  # --- Android 12 trở lên
  android_12:
    color: "#ffffff"      # ← nền trắng cho Android 12+
    image: assets/images/logo.png
    icon_background_color: "#ffffff"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_launcher.png"

  adaptive_icon_foreground: "assets/images/icon_launcher.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  remove_alpha_ios: true

